name: findom
description: "Empowering Indians with CA-level financial wisdom"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.14.0
  firebase_messaging: ^14.7.10

  # Shared Preferences
  shared_preferences: ^2.2.2

  # Notifications
  flutter_local_notifications: ^17.1.2

  # Text to Speech and Speech Recognition
  flutter_tts: ^3.6.3
  #speech_to_text: 6.6.3  âœ… This version avoids Android build errors with Flutter 3.8+

  # Animation
  avatar_glow: ^2.0.2

  # UI & Fonts
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0

  # State management
  provider: ^6.1.2
  get_it: ^7.6.7

  # Form validation and hooks
  flutter_hooks: ^0.20.3
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/onboard1.png
    - assets/images/onboard2.png
    - assets/images/onboard3.png
    - assets/images/mascot.gif
    - assets/images/profile.png
    - assets/images/ca_avatar.png
